# Generated by Django 5.2.7 on 2025-10-25 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CipherKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cipher_type', models.CharField(choices=[('caesar', 'Caesar'), ('affine', 'Affine'), ('hill', 'Hill'), ('playfair', 'Playfair')], max_length=20)),
                ('key_name', models.CharField(help_text='Friendly name for this key', max_length=100)),
                ('key_data', models.JSONField(help_text='JSON object containing key parameters')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cipher_keys',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EncryptionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cipher_type', models.CharField(max_length=20)),
                ('operation', models.CharField(choices=[('encrypt', 'Encrypt'), ('decrypt', 'Decrypt')], max_length=10)),
                ('mode', models.CharField(choices=[('preshared', 'Pre-shared Key'), ('embedded', 'Key Embedded in Message'), ('sent', 'Key Sent Separately')], max_length=20)),
                ('input_text', models.TextField()),
                ('output_text', models.TextField()),
                ('key_used', models.JSONField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'encryption_history',
                'ordering': ['-timestamp'],
            },
        ),
    ]
