# Generated by Django 5.2.7 on 2025-10-26 07:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciphers', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='encryptionhistory',
            name='context',
            field=models.CharField(default='standalone', help_text='Context: standalone, messaging, exercise', max_length=50),
        ),
        migrations.AddField(
            model_name='encryptionhistory',
            name='encryption_steps',
            field=models.JSONField(blank=True, help_text='Step-by-step encryption/decryption process', null=True),
        ),
        migrations.AddField(
            model_name='encryptionhistory',
            name='protection_enabled',
            field=models.BooleanField(default=False, help_text='Whether protection was applied'),
        ),
        migrations.AddField(
            model_name='encryptionhistory',
            name='protection_meta',
            field=models.JSONField(blank=True, help_text='Protection metadata (IV, HMAC, etc.)', null=True),
        ),
        migrations.AddField(
            model_name='encryptionhistory',
            name='protection_type',
            field=models.CharField(blank=True, choices=[('none', 'No Protection'), ('bruteforce', 'Argon2 Key Stretching'), ('frequency', 'Frequency Noise Injection'), ('mitm', 'Diffie-Hellman + HMAC')], max_length=20, null=True),
        ),
        migrations.AddIndex(
            model_name='encryptionhistory',
            index=models.Index(fields=['-timestamp'], name='encryption__timesta_0714dc_idx'),
        ),
        migrations.AddIndex(
            model_name='encryptionhistory',
            index=models.Index(fields=['user', '-timestamp'], name='encryption__user_id_700f59_idx'),
        ),
        migrations.AddIndex(
            model_name='encryptionhistory',
            index=models.Index(fields=['cipher_type', '-timestamp'], name='encryption__cipher__79fec4_idx'),
        ),
    ]
