# Generated by Django 5.2.7 on 2025-10-25 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttackLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cipher_type', models.CharField(max_length=20)),
                ('attack_type', models.CharField(choices=[('brute_force', 'Brute Force'), ('frequency_analysis', 'Frequency Analysis'), ('known_plaintext', 'Known Plaintext')], max_length=30)),
                ('target_text', models.TextField()),
                ('results', models.JSONField()),
                ('success', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'attack_logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
