# Generated by Django 5.2.7 on 2025-10-26 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='protection_enabled',
            field=models.BooleanField(default=True, help_text='Whether encryption protection is active for this conversation'),
        ),
    ]
